### ISSUE TITLE
OS X build failed

### ISSUE THREAD

**Issue by basnijholt** [conda-forge/mshr-feedstock#5]
The builds in this PR https://github.com/conda-forge/mshr-feedstock/pull/3 were successful, but after it got merged [the Travis build failed](https://travis-ci.org/conda-forge/mshr-feedstock/jobs/207682343#L3995) with:
```
ImportError: dlopen(/Users/travis/miniconda3/conda-bld/mshr_1488655233419/_t_env/lib/python2.7/site-packages/_mshr.so, 2): Library not loaded: @rpath/libsuitesparseconfig.4.5.3.dylib
  Referenced from: /Users/travis/miniconda3/conda-bld/mshr_1488655233419/_t_env/lib/libdolfin.2016.2.dylib
  Reason: image not found
TESTS FAILED: mshr-2016.2.0-py27_0
The command "conda build ./recipe" exited with 1.

```

**Comment by minrk** [comment]
Could be a failure to pin dependencies correctly in the fenics package. There was a recent update in the suitesparse package.

**Comment by minrk** [comment]
After a week of propagating builds on Travis, the latest build of mshr has now succeeded.
